### ISSUE TITLE
transfer to gulpjs

### ISSUE THREAD

**Issue by dominictarr** [dominictarr/event-stream#102]
I no longer use this module, and thus do not have very much intrinsic motivation to maintain it.

event-stream is used by many modules in the gulp ecosystem, and so I think the gulp community would be better stewards of event-stream

Would it be okay if I transfered this to the gulp organization?

@gulpjs @callumacrae @contra @gratimax @heikki @phated @robinboehm @tkellen

**Comment by phated** [comment]
Support for event-stream is deprecated. Everything is supposed to move to through2, et al. Maybe just fully deprecate this module?

**Comment by tkellen** [comment]
@phated beat me to it

**Comment by dominictarr** [comment]
it still has 3 million downloads a month, and a lot of gulp-* in the dependants list...
you could of course, update it to through2?

**Comment by phated** [comment]
Mississippi already takes care of that niche. Also, we are no longer going to recommend grab-bag modules. Stream utilities are really not something we want to take on. Event-stream is broken with the latest wip gulp so people will need to update eventually.

**Comment by contra** [comment]
@phated Might be worth updating it then deprecating (if it isn't too tricky) so gulp 4 doesn't break everything that uses it.

@dominictarr Very thoughtful to open discussion btw, thanks!

**Comment by phated** [comment]
@contra no, it's only broken with merge. A better solution than taking on even more responsibility (no thank you) is to open issues on all the repos to update.  Which we already discussed (having a hard time tracking down the issue ATM).

This module definitely should be deprecated. There are other modules that do what it did but for streams2 and 3.  It's fine to let things go.

**Comment by dominictarr** [comment]
Okay well my other thought was to put, basically, an advert for pull-streams at the top of the readme (a project which I _am_ interested in maintaining)

But that seemed like it might not be in the best interests of the community, (although, prehaps they would be very happy with pull-streams) but if glup has moved on anyway, prehaps I'll put a note about upgrading your gulp modules, and about pull-streams too?

**Comment by jdalton** [comment]
@dominictarr There's also a handy [npm command](https://docs.npmjs.com/cli/deprecate) to add a deprecation warning on install.

**Comment by phated** [comment]
Yeah, that sounds like a great idea.  A "For gulp users: use through2 or mississippi or something" section and a "For everyone else: use pull-streams because node streams are busted" section.
