### ISSUE TITLE
How to keep the original stream data unchanged?

### ISSUE THREAD

**Issue by ahrtr** [dominictarr/event-stream#108]
I am using event-stream to process a http request payload.  The payload is a JSON stream (new line separated JSON), and I want to extract all the interested fields. The code is something like below, 
```
import JSONStream from 'JSONStream';
import eventStream from 'event-stream';

async function processPayload(request) {
    const payload = request.payload;
    let indexArray = [];
    await eventStream.pipeline(
        payload, 
        JSONStream.parse(['test']),
        eventStream.mapSync(function(data){
            indexArray.push(data);
        })
    );
    return indexArray;
}
```

Basically the above code works well. But the issue is that it modifies the original payload, so the following operation which depends on the payload as well fails. How can I keep the original data being unchanged? Thanks!

**Comment by right9ctrl** [comment]
@ahrtr Can you pipe the request payload into two streams? See #12
