### ISSUE TITLE
tarball url in package.json could be with https

### ISSUE THREAD

**Issue by ImrePem** [dominictarr/event-stream#109]
Hello devs,

Thank you for your great work.
In packages.json the tarball url is with http. According to [this](https://blog.npmjs.org/post/142077474335/npm-registry-is-now-fully-https), registry.npmjs.org redirect all http requests to https anyway.
We would not append our proxy rules just for this.

**Comment by dominictarr** [comment]
that url is something that npm inserts when it installs it. it's not in the package.json that is checked into git. maybe reinstall it? otherwise it sounds like a bug in npm?
