### ISSUE TITLE
Help me please.

### ISSUE THREAD

**Issue by idkmyusername** [dominictarr/event-stream#112]
I want to make a bot in Discord, the code and the bot itself are ready, only one problem. I write "npm install discord.js —save" and spouts it out: 
npm ERR! Linux 4.4.23+
npm ERR! argv "/data/data/io.tempage.dorynode/files/bin/node" "/data/user/0/io.tempage.dorynode/files/npm/bin/npm-cli.js" "install" "discord.js" "—save"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! file /storage/emulated/0/Download/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token 'c' at 1:1
npm ERR! const Discord = require('discord.js');
npm ERR! ^
npm ERR! File: /storage/emulated/0/Download/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /storage/emulated/0/Download/npm-debug.log
code : 1 / signal : 0
What is this?
How this fix?

**Comment by right9ctrl** [comment]
It looks like you are putting js code into package.json.
