### ISSUE TITLE
Missing git tags and releases

### ISSUE THREAD

**Issue by XhmikosR** [dominictarr/event-stream#113]
The latest git tag/release is 3.0.5. Currently there's no changelog and not having the tags makes it even harder to see what's changed between releases.

**Comment by limonte** [comment]
It's the unfortunate state of the modern JS, zero craps given about transparency, security and backward compatibility :/

**Comment by right9ctrl** [comment]
Github release will be added for future releases.

**Comment by FallingSnow** [comment]
@limonte You called it: https://github.com/dominictarr/event-stream/issues/116

**Comment by wilk** [comment]
This issue is exactly related to SNPM: https://hackernoon.com/secure-npm-ca2fe0e9aeff
Please, support the RFC on NPM: https://github.com/npm/rfcs/pull/16
