### ISSUE TITLE
feature request: expose stream object in es.map

### ISSUE THREAD

**Issue by cambridgemike** [dominictarr/event-stream#65]
It would be nice to call `this.emit('myEvent', data)` from within `.map()`.

**Comment by anko** [comment]
That sounds like a wrong abstraction; if you're calling emit multiple times inside a `map`, it's not really a `map` anymore.  What's wrong with [`es.through`](https://github.com/dominictarr/event-stream#through-write-end)?

**Comment by dominictarr** [comment]
@cambridgemike sorry, am not adding new features. and @anko is correct that you can easily do that with `through`.
