### ISSUE TITLE
npm install: failed to parse package.json

### ISSUE THREAD

**Issue by DennisAhaus** [dominictarr/event-stream#70]
Just wanted to install event-stream via npm with command:
`npm install event-stream -g`
but i only got the same error:

`$ npm install event-stream -g
npm ERR! Failed to parse json
npm ERR! Unexpected end of input
npm ERR! File: C:\Users\myUser\AppData\Roaming\npm-cache\stream-combiner\0.0.4\package\package.jso
n
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\dev\\nodejs\\node.exe" "c:\\dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "
install" "event-stream" "-g"
npm ERR! cwd z:\myService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! file C:\Users\myUser\AppData\Roaming\npm-cache\stream-combiner\0.0.4\package\package.json

npm ERR! code EJSONPARSE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     z:\myService\npm-debug.log
npm ERR! not ok code 0`

**Comment by DennisAhaus** [comment]
Thx for hints. After `npm cache clean` everything works. My fault :+1:

**Comment by vanishcode** [comment]
For npm@5 ,`npm cache clean --force` works.

**Comment by rajkuttie** [comment]
Don't put any  comment line on package.json  File

**Comment by EmadAdly** [comment]
can you try this `npm cache verify`

**Comment by varunrajasekhar** [comment]
try running "npm init"  in your root folder i.e. Eg:  C:\Apps\reactApp

**Comment by ryanmalone** [comment]
npm cache clean did it for me too!

**Comment by hkirkan** [comment]
first install with
`npm install -g ionic` 
and create new project this code `ionic start MyApp -tabs`
and using arrow select "tabs" and press enter will ask a question and press 'Y' press enter 
okey?
