### ISSUE TITLE
flatMap?

### ISSUE THREAD

**Issue by wilsonjackson** [dominictarr/event-stream#73]
It seems like this module could use a flatMap implementation. I've even looked for it in other modules, and can't seem to find a flatMap for node streams (which seems crazy!), only libraries like bacon.js and highland which use their own stream types.

Would you entertain a PR adding flatMap?

**Comment by devinus** [comment]
I actually need this right now. Unsure how to continue...

**Comment by devinus** [comment]
For people finding this in the future, I accomplished a "flatMap" by using this:

```js
        .pipe(es.through(function(data) {
          var stream = this;
          data.forEach(function(r) {
            stream.emit('data', r);
          });
        }))
```

**Comment by dominictarr** [comment]
@devinus it would be better to do `steam.queue(data)` instead of stream.emit('data', data)` because then back pause will work correctly.

**Comment by devinus** [comment]
@dominictarr Interesting. Would you accept a `flatMap` patch using this functionality?

**Comment by devinus** [comment]
I wonder why `mapSync` uses `emit` rather than `queue`.

**Comment by dominictarr** [comment]
@devinus ah, it's probably just old. I don't use this module anymore, i now use https://github.com/dominictarr/pull-streams 

If you publish a flatMap module and then make a pr to include it, i'll merge.
