### ISSUE TITLE
Option to follow Node 0.10 readable stream emit behavior?

### ISSUE THREAD

**Issue by UltCombo** [dominictarr/event-stream#74]
Right now, when I create a new stream (e.g. through `es.readArray()`) it starts emitting data in the `nextTick`.

I'd like it to follow the Node 0.10 behavior, that is, start the stream paused by default and automatically resume it once an `.on('data')` listener/`.pipe()` is attached.

Would this be possible/viable to implement for all methods that return a readable stream?

**Comment by right9ctrl** [comment]
What's your use case? I'd rather not changing the current behavior if possible.
