### ISSUE TITLE
Access to stream combiner

### ISSUE THREAD

**Issue by eddieajau** [dominictarr/event-stream#81]
Just wondering, the `stream-combiner` module is accessible via `es.pipe` but it's not exposed in the documentation. Is it safe to use `es.pipe` in our code?

Thanks in advance.

**Comment by dominictarr** [comment]
that is a legacy api, but it's not gonna change.

**Comment by dominictarr** [comment]
so yes.

**Comment by eddieajau** [comment]
Ok, thanks. 

Would it be better practice to add the `stream-combiner` as an explicit dependency, or is it a case of it doesn't matter for now?

**Comment by dominictarr** [comment]
well, I'm not gonna remove `es.pipe` from event-stream so it would be safe to do so, but if it was my code I'd just depend on stream-combiner directly.

**Comment by eddieajau** [comment]
Perfect. That's what I wanted to know. Thanks so much. Your modules have been a life saver.
