### ISSUE TITLE
npm install event-stream  --> npm ERR! code EJSONPARSE 

### ISSUE THREAD

**Issue by DennisAhaus** [dominictarr/event-stream#86]
$ npm install --save https://github.com/dominictarr/event-stream/tarball/master
npm WARN package.json deliveryapp2@0.0.0 keywords should be an array of strings
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\dev\\iojs\\node.exe" "c:\\dev\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "install
" "--save" "https://github.com/dominictarr/event-stream/tarball/master"
npm ERR! node v1.8.1
npm ERR! npm  v2.8.3
npm ERR! file C:\Users\ahausden\AppData\Roaming\npm-cache\stream-combiner\0.0.4\package\package.json

npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: C:\Users\ahausden\AppData\Roaming\npm-cache\stream-combiner\0.0.4\package\package.jso
n
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:

**Comment by dominictarr** [comment]
this was probably just a network error. does it still happen? why do you want to install from the tarball when you can use the registry?

**Comment by DennisAhaus** [comment]
My first try was install via npm --> `npm install --save event-stream` but this results in same error.

Just now tried again with command `npm install --save event-stream` --> same error.
After that tried command `npm install --save string` --> works

**Comment by dominictarr** [comment]
that is very strange. it worked for me. what version of npm are you using?

**Comment by dominictarr** [comment]
aha, I see in your error message it you are using npm@2.8.3
I installed event stream successfully with 2.9.0

hmm, looking at your log it looks like the problem is actually in stream-combiner... I'm guessing that it half downloaded stream-combiner and you do not have a valid stream-combiner tarball.

bet you this fixes it: `rm -rf ~/npm-cache/stream-combiner`

**Comment by DennisAhaus** [comment]
Thx for your help. Now it works :+1:

**Comment by JaganJonnala** [comment]
Hi, How i can use the above command it showing rm is not an operanble command

**Comment by JaganJonnala** [comment]
![image](https://cloud.githubusercontent.com/assets/10844009/14908225/2622f606-0df2-11e6-8cc7-3c4f3bddbbc9.png)

**Comment by JaganJonnala** [comment]
Getting this error anyone Help me Please.

**Comment by dominictarr** [comment]
@JaganJonnala this is not because of event-stream, the error message says that it couldn't parse the package.json for [inflight](https://www.npmjs.com/package/inflight)

**Comment by dominictarr** [comment]
@JaganJonnala I'd suggest posting the issue on gulp, and trying to install the things that are installed when you install gulp to try and figure out the thing which is broken.

**Comment by cmtp1111** [comment]
C:\Users\Charlie\Desktop\advanced-css-course-master\Natours\new css>npm run compile:sass
npm ERR! file C:\Users\Charlie\Desktop\advanced-css-course-master\Natours\new css\package.json
npm ERR! code EJSONPARSE
npm ERR! Failed to parse json
npm ERR! Unexpected string in JSON at position 214 while parsing '{
npm ERR!   "name": "advanced-css-course-master"'
npm ERR! File: C:\Users\Charlie\Desktop\advanced-css-course-master\Natours\new css\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by cmtp1111** [comment]
other error that im getting now 


C:\Users\Charlie\Desktop\advanced-css-course-master\Natours\new css>npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "new css": Tags may not have any characters that encodeURIComponent encodes.
About to write to C:\Users\Charlie\Desktop\advanced-css-course-master\Natours\new css\package.json:

{
  "name": "",
  "version": ""
}


Is this ok? (yes)
npm ERR! Callback called more than once.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Charlie\AppData\Roaming\npm-cache\_logs\2017-12-10T22_19_20_852Z-debug.log

C:\Users\Charlie\Desktop\advanced-css-course-master\Natours\new css>

**Comment by mctora** [comment]
I had that error but validate my code in this page:

https://translate.googleusercontent.com/translate_c?depth=1&hl=en&prev=search&rurl=translate.google.com.ar&sl=en&sp=nmt4&u=https://jsonlint.com/&usg=ALkJrhh8HS32XFiJMGwPdcio2LaA3H5hFg

**Comment by lusianaharyanti** [comment]
Hello, any body help me? 


![image](https://user-images.githubusercontent.com/37875875/42588250-7222379e-8567-11e8-8905-dc28c76b7fa1.png)
