### ISSUE TITLE
Add a es.chain?

### ISSUE THREAD

**Issue by XeCycle** [dominictarr/event-stream#89]
Currently I have something like this (es6):
```js
function chain(...streams) {
  var [head] = streams;
  var tail = streams.reduce((prev, curr) => prev.pipe(curr));
  return es.duplex(head, tail);
}
```
so that I can write
```js
function formatter() {
  return chain(
    es.split(),
    es.mapSync(...),
    es.stringify()
  );
}

someStream.pipe(formatter());
```

Would you like this added to event-stream?  If yes please also tell me what behaviour you want, e.g. multiple arguments or single array argument, and what to do with empty array, maybe also other corner cases.  I can go PR.

**Comment by dominictarr** [comment]
you should use https://github.com/dominictarr/stream-combiner for that. it also sets up error listeners on the intermediate streams, etc. I'm not adding any new features to event-stream.

**Comment by XeCycle** [comment]
I see, sorry I did not take a look at your other repos.
