### ISSUE TITLE
es.split generate a empty line for trailing newline

### ISSUE THREAD

**Issue by yinrong** [dominictarr/event-stream#90]
es.split is mostly used for processing line by line, however we usually get an empty line at the end of the file. Please remove trailing newline.

**Comment by dominictarr** [comment]
use `es.split({trailing: false})`
see here for documentation: https://www.npmjs.com/package/split

**Comment by yinrong** [comment]
I think event-stream's doc  should have a link to split's doc.

**Comment by n2liquid** [comment]
`event-stream@3.3.4`, the latest version on npm, depends on `split@0.3`, which doesn't implement the `trailing` option. `split` itself is at version 1.0.1. Why is this, and how can we fix it?

**Comment by right9ctrl** [comment]
split upgraded to 1.0.1
