### ISSUE TITLE
Error in parsing when using arrow functions

### ISSUE THREAD

**Issue by drdpedroso** [dominictarr/event-stream#97]
I'm getting queh trying to es.merge my javascript files.

      stream.js:75
         throw er; // Unhandled stream error in pipe.

The error message:
    Error: Error in parsing: "modules/example/controllers/example-controller.js", Line 8: Unexpected token )

My Controller file:

            self.toggleSidenav = () => {
                return $mdSidenav('left').toggle();
            };

Is there some solution for it?

**Comment by dominictarr** [comment]
I think you want https://www.npmjs.com/package/stream-concat instead.
merge doesn't join the input end to end, but just mixes it into one stream.

**Comment by drdpedroso** [comment]
Thanks! That what i'm looking for :)
