### ISSUE TITLE
Dependency to map-stream

### ISSUE THREAD

**Issue by davidbarton** [dominictarr/event-stream#99]
Hi, `package.json` specifies dependency to `"map-stream": "~0.1.0"` which I am unable to find in repo https://github.com/dominictarr/map-stream.

My issue is that installed `map-stream 0.1.0` has custom licence and `map-stream 0.0.6` has MIT (preferable). Can you please take a look and update package dependency?

Reproduce

```
npm init -y
npm i --save map-stream@0.1.0
cat node_modules/map-stream/LICENCE
cat node_modules/map-stream/package.json
```

**Comment by right9ctrl** [comment]
used map-stream@0.0.7
